<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::table('products')->truncate();
        \Illuminate\Support\Facades\DB::table('products')->insert([
            //Áo nam đi biển
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'SEE YOU PIGMENT TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/305200018_Pigment_SeeYou_WHT_1_large.jpg?v=1524526512',
                'price'=> 250000,
                'discount'=>0,
                'description'=>'Áo SEE YOU PIGMENT TEE trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay ngắn cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'DEAD BEAT OLD TIME TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/304300146_OldTime_DeadBeat_BBLU_2_large.jpg?v=1524596609',
                'price'=> 250000,
                'discount'=>0,
                'description'=>'Áo DEAD BEAT OLD TIME TEE trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay ngắn cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'GREAT WHITE PREMIUM TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/304400156_BLK_1_large.jpg?v=1531510717',
                'price'=> 250000,
                'discount'=>5,
                'description'=>'Áo GREAT WHITE PREMIUM TEE trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay ngắn cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'MOVEMENT BLENDED TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/305100022_SGREY_1_large.jpg?v=1531515378',
                'price'=> 250000,
                'discount'=>0,
                'description'=>'Áo MOVEMENT BLENDED TEE trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay ngắn cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'BLENDED',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/305100020_Blended_Avalon_JUN_2_large.jpg?v=1523924570',
                'price'=> 300000,
                'discount'=>10,
                'description'=>'Áo BLENDED trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay ngắn cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'STESS JACKET',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/313000089_Anorak_NoStress_WHT_2_large.jpg?v=1524525523',
                'price'=> 320000,
                'discount'=>0,
                'description'=>'Áo STESS JACKET trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế có mũ, dài tay cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'SLEEVE TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/309000060_StockLS_SunUp_BLU_2_large.jpg?v=1524592995',
                'price'=> 300000,
                'discount'=>0,
                'description'=>'Áo SLEEVE TEE trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay dài cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'PREMIUM TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/304400139_Premium_SunUp_PBLU_2_large.jpg?v=1530291899',
                'price'=> 250000,
                'discount'=>10,
                'description'=>'Áo PREMIUM TEE trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay ngắn cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'STOCK TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/309000056_WHT_2_1024x1024_ebe0fba0-6c7f-46c0-bd5b-3869537b56dd_large.jpg?v=1525716966',
                'price'=> 320000,
                'discount'=>0,
                'description'=>'Áo STOCK TEE trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay dài cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'CLASSIC TEA',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/309500006G_BLK_1_large.jpg?v=1531439107',
                'price'=> 250000,
                'discount'=>20,
                'description'=>'Áo CLASSIC TEA trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay ngắn cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'WORK DAY',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/305200024_IBLU_1_large.jpg?v=1531786725',
                'price'=> 300000,
                'discount'=>0,
                'description'=>'Áo WORK DAY trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay ngắn cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'PASSION',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/305200023_MUS_1_large.jpg?v=1532561558',
                'price'=> 300000,
                'discount'=>0,
                'description'=>'Áo PASSION trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nam họa tiết sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ tròn, tay ngắn cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            //Áo nữ đi biển
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'MORRISON TANK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/408400009_GCM_1_large.jpg?v=1532037589',
                'price'=> 100000,
                'discount'=>0,
                'description'=>'Áo MORRISON TANK trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'DIVE CUTOFF TANK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/403200031_BLKW_2_copy_large.jpg?v=1518653614',
                'price'=> 1500000,
                'discount'=>10,
                'description'=>'Áo DIVE CUTOFF TANK trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'ARDAMA TRIBLEND TANK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/402100019_IND_1_large.jpg?v=1517442825',
                'price'=> 100000,
                'discount'=>0,
                'description'=>'Áo ARDAMA TRIBLEND TANK trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'BASIC TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/404000048_WHT_2_copy_large.jpg?v=1518653891',
                'price'=> 100000,
                'discount'=>0,
                'description'=>'Áo BASIC TEE trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'DIVER TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/404000062_WHT_1_large.jpg?v=1532036286',
                'price'=> 110000,
                'discount'=>10,
                'description'=>'Áo DIVER TEE trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'CALI TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/404000061_DSD_2_large.jpg?v=1532035734',
                'price'=> 100000,
                'discount'=>10,
                'description'=>'Áo CALI TEE trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'MEMORIAL STOW',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/407600012_YEL_2_copy_large.jpg?v=1518658297',
                'price'=> 230000,
                'discount'=>20,
                'description'=>'Áo MEMORIAL STOW trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'ROSE SHRUNKEN',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/405000004_WHT_2_large.jpg?v=1532037927',
                'price'=> 110000,
                'discount'=>0,
                'description'=>'Áo ROSE SHRUNKEN trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'ROSE STOW',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/407600021_PBU_2_large.jpg?v=1532038174',
                'price'=> 150000,
                'discount'=>0,
                'description'=>'Áo ROSE STOW trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'SWELL TD',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/404000053_BLKW_2_large.jpg?v=1517443742',
                'price'=> 150000,
                'discount'=>0,
                'description'=>'Áo SWELL TD trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'SUNBURN',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/402100022_HEA_1_copy_large.jpg?v=1518653532',
                'price'=> 100000,
                'discount'=>20,
                'description'=>'Áo SUNBURN trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'GRAVEYARD',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/401100024_GHE_1_large.jpg?v=1532037005',
                'price'=> 250000,
                'discount'=>0,
                'description'=>'Áo GRAVEYARD trẻ trung phù hợp mặc đi biển',
                'detail'=>'Áo đi biển nữ cá tính,đem lại sự thoải mái, quyến rũ cho phái đẹp tự tin đi biển.Là mẫu áo thiết kế
                hướng đến xu thế nên có thể nói đây là sự lựa chọn thông minh và hợp lí cho những bạn nữ có niềm đam mê đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            //Quần đi biển nam
            [
                'categoryId'=>2,
                'collectionId'=>1,
                'name'=>'SUPPER RANRI',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_CAM_1_large.jpg?v=1532378454',
                'price'=> 300000,
                'discount'=>0,
                'description'=>'Quần nam SUPPER RANRI đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>1,
                'name'=>'BLACKWALL II',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_NAVYTOBACCO_1_large.jpg?v=1516836073',
                'price'=> 200000,
                'discount'=>0,
                'description'=>'Quần nam BLACKWALL II đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>1,
                'name'=>'BLACKWALL III',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_NAVY_RED-1_large.jpg?v=1532104878',
                'price'=> 200000,
                'discount'=>0,
                'description'=>'Quần nam BLACKWALL III đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>1,
                'name'=>'BLACKWALL IV',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_CAVIAR-1_large.jpg?v=1532045768',
                'price'=> 32000,
                'discount'=>30,
                'description'=>'Quần nam BLACKWALL IV đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>1,
                'name'=>'STOKEHOLD',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200037_BLACK-1_large.jpg?v=1524697048',
                'price'=> 250000,
                'discount'=>0,
                'description'=>'Quần nam STOKEHOLD đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'LANDLOPER',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200036_BLACK_1_18801f16-b604-4dcb-bc8f-b98627d9eb54_large.jpg?v=1520011227',
                'price'=> 100000,
                'discount'=>0,
                'description'=>'Quần nam LANDLOPER đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'RANRI',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_CAM_1_copy_large.jpg?v=1520025805',
                'price'=> 300000,
                'discount'=>20,
                'description'=>'Quần nam RANRI đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'ZUBIES I',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_NAVY_1_6e192388-7b3b-4154-b7f8-46a19ebbea46_large.jpg?v=1520009194',
                'price'=> 170000,
                'discount'=>0,
                'description'=>'Quần nam ZUBIES I đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'ZUBIES II',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200035_DENIM_1_large.jpg?v=1516836392',
                'price'=> 170000,
                'discount'=>0,
                'description'=>'Quần nam ZUBIES II đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'ZUBIES III',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200027_BLACKWHITE_1WEB_large.jpg?v=1499389981',
                'price'=> 170000,
                'discount'=>20,
                'description'=>'Quần nam ZUBIES III đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'SUPPER',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200027_BROWNRED_1_large.jpg?v=1532104770',
                'price'=> 120000,
                'discount'=>0,
                'description'=>'Quần nam SUPPER đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'LANDLOPER II',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200036_ARMY_1_large.jpg?v=1520011292',
                'price'=> 100000,
                'discount'=>0,
                'description'=>'Quần nam LANDLOPER II đi biển xu thế năm 2018',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            //Kính đi biển
            [
                'categoryId'=>3,
                'collectionId'=>1,
                'name'=>'EYEGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-6656-28-angle.jpg?sfvrsn=8f6de21b_4',
                'price'=> 70000,
                'discount'=>0,
                'description'=>'Kính EYEGLASSES thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>1,
                'name'=>'UNISEX',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-5832-100-angle.jpg?sfvrsn=b176e21b_4',
                'price'=> 50000,
                'discount'=>0,
                'description'=>'Kính UNISEX thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>1,
                'name'=>'RBSPACE',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/july-18/see-0533-423-angle.jpg?sfvrsn=d2fbe21b_4',
                'price'=> 50000,
                'discount'=>0,
                'description'=>'Kính RBSPACE thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'POLAR',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-8151-39-angle.jpg?sfvrsn=d365e21b_4',
                'price'=> 30000,
                'discount'=>0,
                'description'=>'Kính POLAR thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'JEWERLY',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/june-18/see-0529-106-angle.jpg?sfvrsn=806ce11b_4',
                'price'=> 100000,
                'discount'=>10,
                'description'=>'Kính JEWERLY thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'NECKLACES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/april-18-trunk-show/see-0523-c3176-angle.jpg?sfvrsn=aebce11b_4',
                'price'=> 150000,
                'discount'=>15,
                'description'=>'Kính NECKLACES thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'EARRINGS',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-9287-32-angle.jpg?sfvrsn=4765e21b_4',
                'price'=> 70000,
                'discount'=>0,
                'description'=>'Kính EARRINGS thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'SEAGLASS',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-9651-59-angle.jpg?sfvrsn=b366e21b_4',
                'price'=> 35000,
                'discount'=>0,
                'description'=>'Kính SEAGLASS thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'SALT OPTICS',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/see-1832-31-angle.jpg?sfvrsn=62ece21b_4',
                'price'=> 80000,
                'discount'=>0,
                'description'=>'Kính SALT OPTICS thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'SUNGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-5386-2-angle.jpg?sfvrsn=3175e21b_4',
                'price'=> 100000,
                'discount'=>5,
                'description'=>'Kính SUNGLASSES thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'ODYSSEY',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-5385-3-angle.jpg?sfvrsn=a576e21b_4',
                'price'=> 60000,
                'discount'=>0,
                'description'=>'Kính ODYSSEY thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'AUSETIC',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/july-18/see-9635-1-angle.jpg?sfvrsn=4fd4e21b_4',
                'price'=> 200000,
                'discount'=>10,
                'description'=>'Kính AUSETIC thời thượng, thể hiện sự trẻ trung, năng động.',
                'detail'=>'Kính mắt là phụ kiện đi kèm không thể thiếu của tất cả mọi người trong những dịp đi biển.Vì thế Sea Fashion hướng tới
                những thiết kế trẻ trung, mới lạ, đa dạng về chủng loại lẫn màu sắc.Đây hứa hẹn là một trong những mẫu kính đi biển HOT nhất 2018',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            //Mũ đi biển
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'HUGH HAT',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000256_HUGO_HOT_LIME-1_large.jpg?v=1524766491',
                'price'=> 150000,
                'discount'=>20,
                'description'=>'Mũ HUGH HAT phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'BEACHHEAD',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000250_CAMO_1_large.jpg?v=1516838110',
                'price'=> 70000,
                'discount'=>0,
                'description'=>'Mũ BEACHHEAD phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'BUCKET HAT',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000251_PEACH_1_large.jpg?v=1516838137',
                'price'=> 90000,
                'discount'=>0,
                'description'=>'Mũ BUCKET HAT phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'GAFFTOP HAT',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000264_ORG_1_large.jpg?v=1531507733',
                'price'=> 220000,
                'discount'=>15,
                'description'=>'Mũ GAFFTOP HAT phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'MCGRATH SNAPBACK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000247_BLK_1_large.jpg?v=1517856892',
                'price'=> 120000,
                'discount'=>0,
                'description'=>'Mũ MCGRATH SNAPBACK phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'YBARRA SNAPBACK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000245_NVY_1_large.jpg?v=1516837957',
                'price'=> 150000,
                'discount'=>30,
                'description'=>'Mũ YBARRA SNAPBACK phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'SHANGHAI TRUCKER',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000244_BLACK_1_large.jpg?v=1516837884',
                'price'=> 100000,
                'discount'=>0,
                'description'=>'Mũ SHANGHAI TRUCKER phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'DRYDEN',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000243_NVY_1_large.jpg?v=1516837771',
                'price'=> 100000,
                'discount'=>0,
                'description'=>'Mũ DRYDEN phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'DOC',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000222_BLK_1_large.jpg?v=1499390326',
                'price'=> 90000,
                'discount'=>0,
                'description'=>'Mũ DOC phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'TRIDENT TRUCKER',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000225_NVY_1_large.jpg?v=1517857304',
                'price'=> 230000,
                'discount'=>10,
                'description'=>'Mũ TRIDENT TRUCKER phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'TRIDENT SNAPBACK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000226_BLK_1_large.jpg?v=1524766647',
                'price'=> 150000,
                'discount'=>0,
                'description'=>'Mũ TRIDENT SNAPBACK phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'JOURNEYMAN',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000224_NAVYRED_1_large.jpg?v=1531787265',
                'price'=> 110000,
                'discount'=>0,
                'description'=>'Mũ JOURNEYMAN phong cách,trẻ trung và năng động',
                'detail'=>'Thể hiện phong cách của bạn, cho dù đó là trên đường phố hay trong một cuộc chạy trốn ra bờ biển.Thông 
                hành với mọi lứa tuổi,mọi giới tính.Nói chung là không giới hạn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            //Dép đi biển
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'GUCCI FLIP FLOP SANDAL',
                'images'=>'https://cdn-images.farfetch-contents.com/12/46/33/55/12463355_11564055_255.jpg',
                'price'=> 300000,
                'discount'=>0,
                'description'=>'Dép GUCCI FLIP FLOP SANDAL phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'DOLICE & GABBANA',
                'images'=>'https://cdn-images.farfetch-contents.com/12/96/97/67/12969767_14055828_255.jpg',
                'price'=> 270000,
                'discount'=>0,
                'description'=>'Dép DOLICE & GABBANA phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'FILA',
                'images'=>'https://cdn-images.farfetch-contents.com/12/78/17/77/12781777_13312263_255.jpg',
                'price'=> 300000,
                'discount'=>20,
                'description'=>'Dép FILA phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'ZEUS',
                'images'=>'https://cdn-images.farfetch-contents.com/12/14/71/86/12147186_10187115_255.jpg',
                'price'=> 260000,
                'discount'=>5,
                'description'=>'Dép ZEUS phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'TORY BURCH',
                'images'=>'https://cdn-images.farfetch-contents.com/12/73/29/22/12732922_13864363_255.jpg',
                'price'=> 90000,
                'discount'=>0,
                'description'=>'Dép TORY BURCH phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'VALENTINO',
                'images'=>'https://cdn-images.farfetch-contents.com/12/63/75/03/12637503_12219556_255.jpg',
                'price'=> 130000,
                'discount'=>0,
                'description'=>'Dép VALENTINO phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'ANCIENT GREEK SANDALS',
                'images'=>'https://cdn-images.farfetch-contents.com/12/97/01/97/12970197_13733131_255.jpg',
                'price'=> 120000,
                'discount'=>30,
                'description'=>'Dép ANCIENT GREEK SANDALS phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'GYVENCHY',
                'images'=>'https://cdn-images.farfetch-contents.com/12/53/48/30/12534830_12369562_255.jpg',
                'price'=> 320000,
                'discount'=>0,
                'description'=>'Dép GYVENCHY phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'VARSACE',
                'images'=>'https://cdn-images.farfetch-contents.com/11/89/76/02/11897602_8949578_255.jpg',
                'price'=> 190000,
                'discount'=>20,
                'description'=>'Dép VARSACE phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'FENDI',
                'images'=>'https://cdn-images.farfetch-contents.com/12/98/93/85/12989385_14669777_255.jpg',
                'price'=> 190000,
                'discount'=>0,
                'description'=>'Dép FENDI phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'NIKE',
                'images'=>'https://cdn-images.farfetch-contents.com/13/12/17/25/13121725_14163634_255.jpg',
                'price'=> 70000,
                'discount'=>0,
                'description'=>'Dép NIKE phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'SOPHIA WEBSTER',
                'images'=>'https://cdn-images.farfetch-contents.com/12/95/04/35/12950435_13431168_255.jpg',
                'price'=> 110000,
                'discount'=>0,
                'description'=>'Dép SOPHIA WEBSTER phong cách, cuốn hút',
                'detail'=>'Phong cách thời thượng,thể hiện sự khác biệt là những từ ngữ để diễn tả các thiết kế đến từ Sea Fashion',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ]
        ]);
    }
}
